export type Typenames =
  | 'bigint'
  | 'int8'
  | 'bigserial'
  | 'bit'
  | 'bit varying'
  | 'varbit'
  | 'serial8'
  | 'boolean'
  | 'bool'
  | 'box'
  | 'bytea'
  | 'character'
  | 'char'
  | 'character varying'
  | 'varchar'
  | 'cidr'
  | 'circle'
  | 'date'
  | 'double precision'
  | 'inet'
  | 'integer'
  | 'int'
  | 'int4'
  | 'interval'
  | 'json'
  | 'jsonb'
  | 'line'
  | 'lseg'
  | 'macaddr'
  | 'money'
  | 'numeric'
  | 'path'
  | 'pg_lsn'
  | 'point'
  | 'polygon'
  | 'real'
  | 'float4'
  | 'smallint'
  | 'int2'
  | 'smallserial'
  | 'serial2'
  | 'serial'
  | 'serial4'
  | 'text'
  | 'time'
  | 'without time zone'
  | 'time with time zone'
  | 'timetz'
  | 'timestamp'
  | 'timestamp without time zone'
  | 'timestamp with time zone'
  | 'timestamptz'
  | 'tsquery'
  | 'tsvector'
  | 'txid_snapshot'
  | 'uuid'
  | 'xml'
  | 'ltree'
  | 'lquery';
